import "./style.css"
export const Terms=()=>{
    return(
        <div className="privacy-main">
            <div className="privacy">
                <h1>Discord Terms of Service</h1>
                <p>Last modified: May 7, 2020.</p>
                <p>IMPORTANT NOTICE: THESE TERMS OF SERVICE CONTAIN A BINDING ARBITRATION PROVISION AND CLASS ACTION WAIVER. IT AFFECTS YOUR LEGAL RIGHTS AS DETAILED IN THE DISPUTE RESOLUTION AND CLASS ACTION WAIVER SECTION BELOW. PLEASE READ CAREFULLY.</p>
                <h3>INTRODUCTION AND ACCEPTING THE TERMS</h3>
                <p>Welcome to Discord! These Terms of Service (“Terms”), which include and hereby incorporate the Privacy Policy at https://discord.com/privacy (“Privacy Policy”), are a legal agreement between Discord Inc. and its related companies (the “Company,” “us,” “our,” or "we") and you ("you" or “your”). By using or accessing the Discord application (the “App”) or the website located at https://discord.com (the "Site"), which are collectively referred to as the “Service,” you agree (i) that you are 13 years of age and the minimum age of digital consent in your country, (ii) if you are the age of majority in your jurisdiction or over, that you have read, understood, and accept to be bound by the Terms, and (iii) if you are between 13 (or the minimum age of digital consent, as applicable) and the age of majority in your jurisdiction, that your legal guardian has reviewed and agrees to these Terms.</p>
                <p>The Company reserves the right to update these Terms, which we may do for reasons that include, but are not limited to, complying with changes to the law or reflecting enhancements to Discord. If the changes affect your usage of Discord or your legal rights, we’ll notify you no less than seven days before the changes take effect. Unless we state otherwise, your continued use of the Service after we post modifications will constitute your acceptance of and agreement to those changes. If you object to the changes, your recourse shall be to cease using the Service.</p>
                <h3>RIGHTS TO USE THE SERVICE</h3>
                <p>The Service provides a chat and social platform. The Service may allow you to participate in public and private chat rooms and to utilize messaging features to communicate with other users of the Service. The Service may also allow you to access certain software and/or other content that is available to purchase from the Company. Subject to your compliance with these Terms, the Company grants you a limited, revocable, non-exclusive, non-transferable, non-sublicensable license to use and access the Service. You agree not to (and not to attempt to) (i) use the Service for any use or purpose other than as expressly permitted by these Terms;(ii) copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, attempt to discover any source code, reverse engineer, decompile, disassemble, or otherwise exploit the Service or any portion of the Service, except as expressly permitted in these Terms; or (iii) use data mining, robots, spiders, or similar data gathering and extraction tools on the Service. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by the Company or its licensors, except for the permissions and rights expressly granted in these Terms.</p>
                <p>The Company reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. The Company reserves the right to refuse any user access to the Services without notice for any reason, including but not limited to a violation of the Terms. If you violate these Terms, the Company reserves the right to issue you a warning regarding the violation or immediately terminate or suspend any or all Accounts you have created using the Service. You agree that the Company need not provide you notice before terminating or suspending your Account(s), but it may do so.</p>
                <h3>YOUR ACCOUNT</h3>
                <p>You are responsible for your log-in credentials and for any activity resulting from the use of your log-in credentials or other activity on your account (“Account”) on the Service. Upon launching the App or the Service, if you do not already have an Account, you will be prompted to create one by providing a username and in some cases a password. You may also be required to provide a valid email address or other information to access or utilize certain applications or features. You represent and warrant that the information you provide to us upon registration and at all other times will be true, accurate, current, and complete. We reserve the right to reject any username or to terminate your username or prevent use of a username in our sole discretion, and without any liability to you. You understand and agree that other users of the Service may have the same username as you, however, users will be differentiated by a number identifier that may or may not be visible to you or other users. You will ensure that your e-mail address is kept accurate and up-to-date at all times. If we allow you to use the App without creating an Account (e.g., if we make available a single-session use feature), any username you select for use in connection with the App will be available for other users after your session ends. You are responsible for maintaining the confidentiality of your log-in credentials and are fully responsible for all activities that occur through the use of your credentials or otherwise on your Account. You agree to notify us immediately if you believe the confidentiality of your log-in credentials has been compromised or if you suspect unauthorized use of your Account. You agree that we will not be liable for any loss or damage arising from unauthorized use of your credentials.</p>
                <h3>COMMUNICATIONS</h3>
                <p>You agree to receive communications from us electronically, such as email, text, or mobile push notices, or notices and messages on the Service. For any direct marketing messages, we will ensure that we obtain your consent first, and also make it easy for you to opt out — we don’t want to send you messages you don’t want.</p>
                <p>By using the Service or providing information to us, you agree that we may communicate with you electronically regarding security, privacy, and administrative issues relating to your use of the Service, and that all agreements, notices, disclosures, and other communications that Discord provides to you electronically satisfy any legal requirements that such communications be in writing.</p>
                <p>You may use the Service to send messages to other users of the Service. You agree that your use of the Service will not include sending unsolicited marketing messages or broadcasts (i.e., spam). We may utilize a variety of means to block spammers and abusers from using the Service. If you believe spam originated from the Service, please email us immediately at support@discord.com.</p>

            </div>
            
        </div>
    )
}